---
title: "Figures"
author: "R.Welch"
date: "2025-04-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

libraries
```{r : reading libraries, include= FALSE}
packages <- c("tidyverse", "readxl", "dplyr", "magrittr", "mixtools", "emmeans", "readr","data.table", "lubridate", "ggplot2", "skimr", "ggstatsplot","summarytools", "knitr", "here", "ggthemes", "Amelia", "tidyr", "naniar", "stringr", "janitor", "ggbreak", "patchwork", "plotrix", "viridis", "hrbrthemes")

lapply(packages, library, character.only = TRUE)
```


```{r : set up #2}
# read in data
Nov22_Nov23_minimal_dataset <- read.csv("C:/Users/md1rwe/Documents/Data extractions from I-CAH/Feb 2025/SDM_stats/data/Nov22-Nov23.csv", header=T, na.strings= c("", "NA"))

Nov23_Nov24_minimal_dataset <- read.csv("C:/Users/md1rwe/Documents/Data extractions from I-CAH/Feb 2025/SDM_stats/data/Nov23-Nov24.csv", header=T, na.strings= c("", "NA"))

Nov24_Feb25_minimal_dataset <- read.csv("C:/Users/md1rwe/Documents/Data extractions from I-CAH/Feb 2025/SDM_stats/data/Feb25-Nov24.csv", header=T, na.strings= c("", "NA"))

# making Nov23-Feb25
Nov23_Feb25_minimal_dataset <- rbind(Nov23_Nov24_minimal_dataset, Nov24_Feb25_minimal_dataset)

# remove the two now individual frames
remove(Nov23_Nov24_minimal_dataset, Nov24_Feb25_minimal_dataset)

# given that stats here will often be split by sex, NK says to remove the single 'Not Assigned' (add note of this patient's data) to make plots easier to read. They're in the Nov23-Feb25 dataframe
# extract this patient's data into its own frame before removing it
NA_patient <- subset(Nov23_Feb25_minimal_dataset, Nov23_Feb25_minimal_dataset$Sex.at.birth.x == "Not Assigned")

Nov23_Feb25_minimal_dataset <- Nov23_Feb25_minimal_dataset [!Nov23_Feb25_minimal_dataset$Sex.at.birth.x == "Not Assigned",]

# colours
myColours <- c("purple", "lightblue", "grey")
```

``` {r :  Oscars function :)}
#
# MDBoxPlot <- function (MDS, Param, splitType, ttl)
#

# anthropometry

  HeightPlot22_23 <- MDBoxPlot(Nov22_Nov23_minimal_dataset, "Height..cm.", "SBS", "Height 22_23")

  HeightPlot23_25 <- MDBoxPlot(Nov23_Feb25_minimal_dataset, "Height..cm.", "SBS", "Height 23_25")
 
  WeightPlot22_23 <- MDBoxPlot(Nov22_Nov23_minimal_dataset, "Weight..kg.", "SBS", "Weight 22_23")
     
  WeightPlot23_25 <- MDBoxPlot(Nov23_Feb25_minimal_dataset, "Weight..kg.", "SBS", "Weight 23_25")
  
  BMIPlot_22_23 <- MDBoxPlot(Nov22_Nov23_minimal_dataset, "BMI", "SBS", "BMI 22_23")
  
  BMIPlot_23_25 <- MDBoxPlot(Nov23_Feb25_minimal_dataset, "BMI", "SBS", "BMI 23_25")  
  
# biomarkers
  
  TestoPlot22_23 <- MDBoxPlot(Nov22_Nov23_minimal_dataset, "Total.testosterone.value", "NTEO", "Testosterone 22_23")

  TestoPlot23_25 <- MDBoxPlot(Nov23_Feb25_minimal_dataset, "Total.testosterone.value", "NTEO", "Testosterone 23_25")
  
  ReninPlot22_23 <- MDBoxPlot(Nov22_Nov23_minimal_dataset, "Renin.value", "NTEO", "Renin 22_23")

  ReninPlot23_25 <- MDBoxPlot(Nov23_Feb25_minimal_dataset, "Renin.value", "NTEO", "Renin 23_25")
  
  OHPPlot22_23 <- MDBoxPlot(Nov22_Nov23_minimal_dataset, "X17.OHP.value", "NTEO", "17 OHP 22_23")
  
  OHPPlot23_25 <- MDBoxPlot(Nov23_Feb25_minimal_dataset, "X17.OHP.value", "NTEO", "17 OHP 23_25")

```

```{r : weight box plot}
# make new data frame
raw_weight_22_23 <- select(Nov22_Nov23_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "Weight..kg."))

# change Centre ID to factor variable (to be able to use it as x axis)
raw_weight_22_23$Centre.ID.x <- as.factor(raw_weight_22_23$Centre.ID.x)

# remove rows with NA for weight
raw_weight_22_23 <- raw_weight_22_23 [!is.na(raw_weight_22_23$Weight..kg.),]

# basic box plot
graph_weight_22_23 <- ggplot(data = raw_weight_22_23, aes(x = Centre.ID.x, y = Weight..kg., fill = Sex.at.birth.x)) +
  geom_boxplot() +
  labs(title = "Weight distribution 22-23", x = "Centre ID", y = "Weight (kg)") +
  theme_minimal() +
  scale_fill_manual(values = myColours)

# +
#   geom_point(position = position_dodge(width = 0.75), aes(group = Sex.at.birth.x))

# view
graph_weight_22_23


## for other time frame

# make new height data frame
raw_weight_23_25 <- select(Nov23_Feb25_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "Weight..kg."))

# change Centre ID to factor variable (to be able to use it as x axis)
raw_weight_23_25$Centre.ID.x <- as.factor(raw_weight_23_25$Centre.ID.x)

# remove rows with NA for weight
raw_weight_23_25 <- raw_weight_23_25 [!is.na(raw_weight_23_25$Weight..kg.),]

# basic box plot
graph_weight_23_25 <- ggplot(data = raw_weight_23_25, aes(x = Centre.ID.x, y = Weight..kg., fill = Sex.at.birth.x)) +
  geom_boxplot() +
  labs(title = "Weight distribution 23-25", x = "Centre ID", y = "Weight (kg)") +
  theme_minimal() +
  scale_fill_manual(values = myColours)

# view
graph_weight_23_25
```

```{r : weight violin plot}
#NOT ENOUGH DATA FOR VIOLIN PLOTS

violin_weight_22_23 <- ggplot(data = raw_weight_22_23, aes(x = Centre.ID.x, y = Weight..kg., fill = Sex.at.birth.x)) +
  geom_violin(drop = FALSE) +
  labs(title = "Weight distribution 22-23", x = "Centre ID", y = "Weight (kg)") +
  theme_minimal() +
  scale_fill_manual(values = myColours)

violin_weight_22_23

violin_weight_23_25 <- ggplot(data = raw_weight_23_25, aes(x = Centre.ID.x, y = Weight..kg., fill = Sex.at.birth.x)) +
  geom_violin(drop = FALSE) +
  labs(title = "Weight distribution 23-25", x = "Centre ID", y = "Weight (kg)") +
  theme_minimal() +
  scale_fill_manual(values = myColours)


violin_weight_23_25

```



```{r : height box plot}
# make new data frame
raw_height_22_23 <- select(Nov22_Nov23_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "Height..cm."))

# change Centre ID to factor variable (to be able to use it as x axis)
raw_height_22_23$Centre.ID.x <- as.factor(raw_height_22_23$Centre.ID.x)

# remove rows with NA for height
raw_height_22_23 <- raw_height_22_23 [!is.na(raw_height_22_23$Height..cm.),]

# basic box plot
graph_height_22_23 <- ggplot(data = raw_height_22_23, aes(x = Centre.ID.x, y = Height..cm., fill = Sex.at.birth.x)) +
  geom_boxplot() +
  labs(title = "Height distribution 22-23", x = "Centre ID", y = "Height (cm)") +
  theme_minimal() +
  scale_fill_manual(values = myColours)

# view
graph_height_22_23


## for other time frame

# make new height data frame
raw_height_23_25 <- select(Nov23_Feb25_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "Height..cm."))

# change Centre ID to factor variable (to be able to use it as x axis)
raw_height_23_25$Centre.ID.x <- as.factor(raw_height_23_25$Centre.ID.x)

# remove rows with NA for height
raw_height_23_25 <- raw_height_23_25 [!is.na(raw_height_23_25$Height..cm.),]

# basic box plot
graph_height_23_25 <- ggplot(data = raw_height_23_25, aes(x = Centre.ID.x, y = Height..cm., fill = Sex.at.birth.x)) +
  geom_boxplot() +
  labs(title = "Height distribution 23-25", x = "Centre ID", y = "Height (cm)") +
  theme_minimal() +
  scale_fill_manual(values = myColours)

# view
graph_height_23_25
```

```{r : age histogram plot}
# decided to do histogram because I'm looking at the distribution of ages rather than the stats

# make new data frame
raw_age_22_23 <- select(Nov22_Nov23_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "Age"))

# change Centre ID to factor variable (to be able to use it as x axis)
raw_age_22_23$Centre.ID.x <- as.factor(raw_age_22_23$Centre.ID.x)

# remove rows with NA for height
raw_age_22_23 <- raw_age_22_23 [!is.na(raw_age_22_23$Age),]

# histogram
graph_age_22_23 <- ggplot(raw_age_22_23, aes(x = Age, fill = Sex.at.birth.x)) +
  geom_histogram(binwidth = 2) +
  labs(title = "Age distibution 22-23", x = "Age", y = "Frequency") +
  theme_minimal() +
  scale_fill_manual(values = myColours)

# view
graph_age_22_23


## for other time frame

# make new data frame
raw_age_23_25 <- select(Nov23_Feb25_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "Age"))

# change Centre ID to factor variable (to be able to use it as x axis)
raw_age_23_25$Centre.ID.x <- as.factor(raw_age_23_25$Centre.ID.x)

# remove rows with NA for height
raw_age_23_25 <- raw_age_23_25 [!is.na(raw_age_23_25$Age),]

# histogram
graph_age_23_25 <- ggplot(raw_age_23_25, aes(x = Age, fill = Sex.at.birth.x)) +
  geom_histogram(binwidth = 2) +
  labs(title = "Age distibution 23-25", x = "Age", y = "Frequency") +
  theme_minimal() +
  scale_fill_manual(values = myColours)

# view
graph_age_23_25
```


```{r : BMI box plot}
# make new data frame
raw_BMI_22_23 <- select(Nov22_Nov23_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "BMI"))

# change Centre ID to factor variable (to be able to use it as x axis)
raw_BMI_22_23$Centre.ID.x <- as.factor(raw_BMI_22_23$Centre.ID.x)

# remove rows with NA for height
raw_BMI_22_23 <- raw_BMI_22_23 [!is.na(raw_BMI_22_23$BMI),]

# basic box plot
graph_BMI_22_23 <- ggplot(data = raw_BMI_22_23, aes(x = Centre.ID.x, y = BMI, fill = Sex.at.birth.x)) +
  geom_boxplot() +
  labs(title = "BMI distribution 22-23", x = "Centre ID", y = "BMI") +
  theme_minimal() +
  scale_fill_manual(values = myColours)

# view
graph_BMI_22_23


## for other time frame

# make new data frame
raw_BMI_23_25 <- select(Nov23_Feb25_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "BMI"))

# change Centre ID to factor variable (to be able to use it as x axis)
raw_BMI_23_25$Centre.ID.x <- as.factor(raw_BMI_23_25$Centre.ID.x)

# remove rows with NA for height
raw_BMI_23_25 <- raw_BMI_23_25 [!is.na(raw_BMI_23_25$BMI),]

# basic box plot
graph_BMI_23_25 <- ggplot(data = raw_BMI_23_25, aes(x = Centre.ID.x, y = BMI, fill = Sex.at.birth.x)) +
  geom_boxplot() +
  labs(title = "BMI distribution 23-25", x = "Centre ID", y = "BMI") +
  theme_minimal() +
  scale_fill_manual(values = myColours)

# view
graph_BMI_23_25
```

```{r : BMI violin plot}
violin_BMI_22_23 <- ggplot(data = raw_BMI_22_23, aes(x = Centre.ID.x, y = BMI, fill = Sex.at.birth.x)) +
  geom_violin(drop = FALSE) +
  labs(title = "BMI distribution 22-23", x = "Centre ID", y = "BMI") +
  theme_minimal() +
  scale_fill_manual(values = myColours)

violin_BMI_22_23

violin_BMI_23_25 <- ggplot(data = raw_BMI_23_25, aes(x = Centre.ID.x, y = BMI, fill = Sex.at.birth.x)) +
  geom_violin(drop = FALSE) +
  labs(title = "BMI distribution 23-25", x = "Centre ID", y = "BMI") +
  theme_minimal() +
  scale_fill_manual(values = myColours)


violin_BMI_23_25
```


```{r : 17-OHP box plot}
# make new data frame
raw_17OHP_22_23 <- select(Nov22_Nov23_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "X17.OHP.value"))

# change Centre ID to factor variable (to be able to use it as x axis)
raw_17OHP_22_23$Centre.ID.x <- as.factor(raw_17OHP_22_23$Centre.ID.x)

# remove rows with NA for height
raw_17OHP_22_23 <- raw_17OHP_22_23 [!is.na(raw_17OHP_22_23$X17.OHP.value),]

# basic box plot
graph_17OHP_22_23 <- ggplot(data = raw_17OHP_22_23, aes(x = Centre.ID.x, y = X17.OHP.value)) +
  geom_boxplot() +
  labs(title = "17-OHP distribution 22-23", x = "Centre ID", y = "17-OHP value (nmol/L)") +
  theme_minimal() +
  scale_fill_manual(values = myColours)

# view
graph_17OHP_22_23


## for other time frame

# make new data frame
raw_17OHP_23_25 <- select(Nov23_Feb25_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "X17.OHP.value"))

# change Centre ID to factor variable (to be able to use it as x axis)
raw_17OHP_23_25$Centre.ID.x <- as.factor(raw_17OHP_23_25$Centre.ID.x)

# remove rows with NA for height
raw_17OHP_23_25 <- raw_17OHP_23_25 [!is.na(raw_17OHP_23_25$X17.OHP.value),]

# basic box plot
graph_17OHP_23_25 <- ggplot(data = raw_17OHP_23_25, aes(x = Centre.ID.x, y = X17.OHP.value)) +
  geom_boxplot() +
  labs(title = "17-OHP distribution 23-25", x = "Centre ID", y = "17-OHP value (nmol/L)") +
  theme_minimal() +
  scale_fill_manual(values = myColours) +
  scale_y_break(c(400,1200), scale = 0.25)

# view
graph_17OHP_23_25
```

```{r : andro box plot}
# make new data frame
raw_andro_22_23 <- select(Nov22_Nov23_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "Androstenedione.value"))

# change Centre ID to factor variable (to be able to use it as x axis)
raw_andro_22_23$Centre.ID.x <- as.factor(raw_andro_22_23$Centre.ID.x)

# remove rows with NA for height
raw_andro_22_23 <- raw_andro_22_23 [!is.na(raw_andro_22_23$Androstenedione.value),]

# basic box plot
graph_andro_22_23 <- ggplot(data = raw_andro_22_23, aes(x = Centre.ID.x, y = Androstenedione.value, fill = Sex.at.birth.x)) +
  geom_boxplot() +
  labs(title = "Andro distribution 22-23", x = "Centre ID", y = "Andro value (nmol/L)") +
  theme_minimal() +
  scale_fill_manual(values = myColours) +
  facet_wrap(~ Sex.at.birth.x, scales = "free")

# view
graph_andro_22_23


## for other time frame

# make new data frame
raw_andro_23_25 <- select(Nov23_Feb25_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "Androstenedione.value"))

# change Centre ID to factor variable (to be able to use it as x axis)
raw_andro_23_25$Centre.ID.x <- as.factor(raw_andro_23_25$Centre.ID.x)

# remove rows with NA for height
raw_andro_23_25 <- raw_andro_23_25 [!is.na(raw_andro_23_25$Androstenedione.value),]

# basic box plot
graph_andro_23_25 <- ggplot(data = raw_andro_23_25, aes(x = Centre.ID.x, y = Androstenedione.value, fill = Sex.at.birth.x)) +
  geom_boxplot() +
  ylim(0,35) +
  labs(title = "Andro distribution 23-25", x = "Centre ID", y = "Andro value (nmol/L)") +
  theme_minimal() +
  scale_fill_manual(values = myColours)

# basic box plot, split by sex
graph_andro_23_25_sex_split <- ggplot(data = raw_andro_23_25, aes(x = Centre.ID.x, y = Androstenedione.value, fill = Sex.at.birth.x)) +
  geom_boxplot() +
  ylim(0,35) +
  labs(title = "Andro distribution 23-25 (sex split)", x = "Centre ID", y = "Andro value (nmol/L)") +
  theme_minimal() +
  scale_fill_manual(values = myColours) +
  facet_wrap(~ Sex.at.birth.x, scales = "free")

# view
graph_andro_23_25

# attempt to add in axes break

```

```{r : testosterone box plot}
# make new data frame
raw_testo_22_23 <- select(Nov22_Nov23_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "Total.testosterone.value"))

# change Centre ID to factor variable (to be able to use it as x axis)
raw_testo_22_23$Centre.ID.x <- as.factor(raw_testo_22_23$Centre.ID.x)

# remove rows with NA for height
raw_testo_22_23 <- raw_testo_22_23 [!is.na(raw_testo_22_23$Total.testosterone.value),]

# basic box plot
graph_testo_22_23 <- ggplot(data = raw_testo_22_23, aes(x = Centre.ID.x, y = Total.testosterone.value, fill = Sex.at.birth.x)) +
  geom_boxplot() +
  ylim(0, 22) +
  labs(title = "Testosterone distribution 22-23", x = "Centre ID", y = "Testosterone value (nmol/L)") +
  theme_minimal() +
  scale_fill_manual(values = myColours)

# basic box plot, split by sex
graph_testo_22_23_sex_split <- ggplot(data = raw_testo_22_23, aes(x = Centre.ID.x, y = Total.testosterone.value, fill = Sex.at.birth.x)) +
  geom_boxplot() +
  ylim(0, 22) +
  labs(title = "Testosterone distribution 22-23 (split by sex)", x = "Centre ID", y = "Testosterone value (nmol/L)") +
  theme_minimal() +
  scale_fill_manual(values = myColours) +
  facet_wrap(~ Sex.at.birth.x)

# view
graph_testo_22_23
# view
graph_testo_22_23_sex_split



## for other time frame

# make new data frame
raw_testo_23_25 <- select(Nov23_Feb25_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "Total.testosterone.value"))

# change Centre ID to factor variable (to be able to use it as x axis)
raw_testo_23_25$Centre.ID.x <- as.factor(raw_testo_23_25$Centre.ID.x)

# remove rows with NA for height
raw_testo_23_25 <- raw_testo_23_25 [!is.na(raw_testo_23_25$Total.testosterone.value),]

# basic box plot
graph_testo_23_25 <- ggplot(data = raw_testo_23_25, aes(x = Centre.ID.x, y = Total.testosterone.value, fill = Sex.at.birth.x)) +
  geom_boxplot() +
  labs(title = "Testosterone distribution 23-25", x = "Centre ID", y = "Testosterone value (nmol/L)") +
  theme_minimal() +
  scale_fill_manual(values = myColours)

# basic box plot, split by sex
graph_testo_23_25_sex_split <- ggplot(data = raw_testo_23_25, aes(x = Centre.ID.x, y = Total.testosterone.value, fill = Sex.at.birth.x)) +
  geom_boxplot() +
  labs(title = "Testosterone distribution 23-25 (split by sex)", x = "Centre ID", y = "Testosterone value (nmol/L)") +
  theme_minimal() +
  scale_fill_manual(values = myColours) +
  facet_wrap(~ Sex.at.birth.x)

# view
graph_testo_23_25
# view
graph_testo_23_25_sex_split
```

```{r : renin plasma activity box plot}
# check units

# make new data frame
raw_renin_22_23 <- select(Nov22_Nov23_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "Renin.value" ))

# change Centre ID to factor variable (to be able to use it as x axis)
raw_renin_22_23$Centre.ID.x <- as.factor(raw_renin_22_23$Centre.ID.x)

# remove rows with NA for height
raw_renin_22_23 <- raw_renin_22_23 [!is.na(raw_renin_22_23$Renin.value),]

# basic box plot
graph_renin_22_23 <- ggplot(data = raw_renin_22_23, aes(x = Centre.ID.x, y = Renin.value, fill = Sex.at.birth.x)) +
  geom_boxplot() +
  labs(title = "Renin plasma activity 22-23", x = "Centre ID", y = "Renin plasma activity value (uIU/ml)") +
  theme_minimal() +
  scale_fill_manual(values = myColours)

# basic box plot, split by sex
graph_renin_22_23_sex_split <- ggplot(data = raw_renin_22_23, aes(x = Centre.ID.x, y = Renin.value, fill = Sex.at.birth.x)) +
  geom_boxplot() +
  labs(title = "Renin plasma activity 22-23 (split by sex)", x = "Centre ID", y = "Renin plasma activity value (uIU/ml)") +
  theme_minimal() +
  scale_fill_manual(values = myColours) +
  facet_wrap(~ Sex.at.birth.x)

# view
graph_renin_22_23
# view
graph_renin_22_23_sex_split


## for other time frame

# make new data frame
raw_renin_23_25 <- select(Nov23_Feb25_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "Renin.value" ))

# change Centre ID to factor variable (to be able to use it as x axis)
raw_renin_23_25$Centre.ID.x <- as.factor(raw_renin_23_25$Centre.ID.x)

# remove rows with NA for height
raw_renin_23_25 <- raw_renin_23_25 [!is.na(raw_renin_23_25$Renin.value),]

# basic box plot
graph_renin_23_25 <- ggplot(data = raw_renin_23_25, aes(x = Centre.ID.x, y = Renin.value, fill = Sex.at.birth.x)) +
  geom_boxplot() +
  labs(title = "Renin plasma activity 23-25", x = "Centre ID", y = "Renin plasma activity value (uIU/ml)") +
  theme_minimal() +
  scale_fill_manual(values = myColours)

# basic box plot, split by sex
graph_renin_23_25_sex_split <- ggplot(data = raw_renin_23_25, aes(x = Centre.ID.x, y = Renin.value, fill = Sex.at.birth.x)) +
  geom_boxplot() +
  labs(title = "Renin plasma activity 23-25 (split by sex)", x = "Centre ID", y = "Renin plasma activity value (uIU/ml)") +
  theme_minimal() +
  scale_fill_manual(values = myColours) +
  facet_wrap(~ Sex.at.birth.x)

# view
graph_renin_23_25
# view
graph_renin_23_25_sex_split
```



```{r : end of script section}
print("Script complete")
```