---
title: "medicationDataAndPlots"
author: "R.Welch"
date: "2025-04-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

libraries
```{r : reading libraries, include= FALSE}
packages <- c("tidyverse", "readxl", "dplyr", "magrittr", "mixtools", "emmeans", "readr","data.table", "lubridate", "ggplot2", "skimr", "ggstatsplot","summarytools", "knitr", "here", "ggthemes", "Amelia", "tidyr", "naniar", "stringr", "janitor", "ggbreak", "patchwork", "plotrix", "viridis", "hrbrthemes", "showtext")

lapply(packages, library, character.only = TRUE)
```

```{r : set up #2}
# read in data
Nov22_Nov23_minimal_dataset <- read.csv("C:/Users/md1rwe/Documents/Data extractions from I-CAH/Feb 2025/SDM_stats/data/Nov22-Nov23.csv", header=T, na.strings= c("", "NA"))

Nov23_Nov24_minimal_dataset <- read.csv("C:/Users/md1rwe/Documents/Data extractions from I-CAH/Feb 2025/SDM_stats/data/Nov23-Nov24.csv", header=T, na.strings= c("", "NA"))

Nov24_Feb25_minimal_dataset <- read.csv("C:/Users/md1rwe/Documents/Data extractions from I-CAH/Feb 2025/SDM_stats/data/Feb25-Nov24.csv", header=T, na.strings= c("", "NA"))

# making all_data_22_25
all_data_22_25 <- rbind(Nov22_Nov23_minimal_dataset, Nov23_Nov24_minimal_dataset, Nov24_Feb25_minimal_dataset)
# remove NA patient
all_data_22_25 <- all_data_22_25 [!all_data_22_25$Sex.at.birth.x == "Not Assigned",]

# making Nov23-Feb25
Nov23_Feb25_minimal_dataset <- rbind(Nov23_Nov24_minimal_dataset, Nov24_Feb25_minimal_dataset)

# remove the two now individual frames
remove(Nov23_Nov24_minimal_dataset, Nov24_Feb25_minimal_dataset)

# format type of columns correctly
Nov23_Feb25_minimal_dataset$HC_equivalent_daily_dose_per_BSA <- as.numeric(Nov23_Feb25_minimal_dataset$HC_equivalent_daily_dose_per_BSA)

Nov23_Feb25_minimal_dataset$HC_equivalent_daily_dose_per_kg <- as.numeric(Nov23_Feb25_minimal_dataset$HC_equivalent_daily_dose_per_kg)

Nov23_Feb25_minimal_dataset$Date.y <- as.Date(Nov23_Feb25_minimal_dataset$Date.y, format = "%d/%m/%Y")


# given that stats here will often be split by sex, NK says to remove the single 'Not Assigned' (add note of this patient's data) to make plots easier to read. They're in the Nov23-Feb25 dataframe
# extract this patient's data into its own frame before removing it
NA_patient <- subset(Nov23_Feb25_minimal_dataset, Nov23_Feb25_minimal_dataset$Sex.at.birth.x == "Not Assigned")

Nov23_Feb25_minimal_dataset <- Nov23_Feb25_minimal_dataset [!Nov23_Feb25_minimal_dataset$Sex.at.birth.x == "Not Assigned",]

# colours
myColours <- c("purple", "lightblue", "grey")

# histogram colours
histColours <- c("red", "springgreen2", "royalblue2")
```

```{r : split therapy types}
# let's make a new frame to determine which patients are on single or combined therapies:
therapy_22_23 <- Nov22_Nov23_minimal_dataset

# need to add in column for dose_time_hours_4 for 22-23 data set
therapy_22_23$dose_time_hours_4 <- NA

  #select(Nov22_Nov23_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "CO.ID.x",  "Medicine_1.x", "Dose_1", "Standardised.doses_1", "Medicine_2.x", "Dose_2", "Standardised.doses_2", "Medicine_3.x", "Dose_3", "Standardised.doses_3", "Medicine_4.x", "Dose_4", "Standardised.doses_4", "HC_equivalent_daily_dose_1_1"))

therapy_23_25 <- Nov23_Feb25_minimal_dataset
  #select(Nov23_Feb25_minimal_dataset, c("Centre.ID.x", "Sex.at.birth.x", "CO.ID.x", "Medicine_1.x", "Dose_1", "Standardised.doses_1", "Medicine_2.x", "Dose_2", "Standardised.doses_2", "Medicine_3.x", "Dose_3", "Standardised.doses_3", "Medicine_4.x", "Dose_4", "Standardised.doses_4", "HC_equivalent_daily_dose_1_1"))

# need to add in column for dose_time_hours_4 for 23-25 data set
therapy_23_25$dose_time_hours_4 <- NA

therapy_22_23$Total_raw_dose <- rowSums(therapy_22_23 [,c("Dose_1", "Dose_2", "Dose_3", "Dose_4")], na.rm =TRUE)

therapy_23_25$Total_raw_dose <- rowSums(therapy_23_25 [,c("Dose_1", "Dose_2", "Dose_3", "Dose_4")], na.rm =TRUE)

# remove rows with NO MEDICATION DATA
therapy_22_23 <- therapy_22_23 [!is.na(therapy_22_23$Medicine_1.x),]
therapy_23_25 <- therapy_23_25 [!is.na(therapy_23_25$Medicine_1.x),]

therapy_22_23$"single/combined" <- NA
therapy_23_25$"single/combined" <- NA

# check for single vs combined
therapy_22_23$`single/combined` <-
  ifelse(!is.na(therapy_22_23$Medicine_1.x) &
         (is.na(therapy_22_23$Medicine_2.x) & is.na(therapy_22_23$Medicine_3.x) & is.na(therapy_22_23$Medicine_4.x) |
          therapy_22_23$Medicine_1.x == therapy_22_23$Medicine_2.x & is.na(therapy_22_23$Medicine_3.x) & is.na(therapy_22_23$Medicine_4.x) |
          therapy_22_23$Medicine_1.x == therapy_22_23$Medicine_2.x & therapy_22_23$Medicine_1.x == therapy_22_23$Medicine_3.x & is.na(therapy_22_23$Medicine_4.x) |
          therapy_22_23$Medicine_1.x == therapy_22_23$Medicine_2.x & therapy_22_23$Medicine_1.x == therapy_22_23$Medicine_3.x & therapy_22_23$Medicine_1.x == therapy_22_23$Medicine_4.x),
          as.character("single"),
          as.character("combined"))


therapy_23_25$`single/combined` <-
  ifelse(!is.na(therapy_23_25$Medicine_1.x) &
         (is.na(therapy_23_25$Medicine_2.x) & is.na(therapy_23_25$Medicine_3.x) & is.na(therapy_23_25$Medicine_4.x) |
          therapy_23_25$Medicine_1.x == therapy_23_25$Medicine_2.x & is.na(therapy_23_25$Medicine_3.x) & is.na(therapy_23_25$Medicine_4.x) |
          therapy_23_25$Medicine_1.x == therapy_23_25$Medicine_2.x & therapy_23_25$Medicine_1.x == therapy_23_25$Medicine_3.x & is.na(therapy_23_25$Medicine_4.x) |
          therapy_23_25$Medicine_1.x == therapy_23_25$Medicine_2.x & therapy_23_25$Medicine_1.x == therapy_23_25$Medicine_3.x & therapy_23_25$Medicine_1.x == therapy_23_25$Medicine_4.x),
          as.character("single"),
          as.character("combined"))

therapy_22_23_single <- therapy_22_23[therapy_22_23$`single/combined` == "single",]
therapy_23_25_single <- therapy_23_25[therapy_23_25$`single/combined` == "single",]

therapy_22_23_combined <- therapy_22_23[therapy_22_23$`single/combined` == "combined",] 
therapy_23_25_combined <- therapy_23_25[therapy_23_25$`single/combined` == "combined",]

# make therapy 22-25
all_therapy_22_25_single <- rbind(therapy_22_23_single, therapy_23_25_single)
all_therapy_22_25_combined <- rbind(therapy_22_23_combined, therapy_23_25_combined)

write.csv(all_therapy_22_25_single, "C:/Users/md1rwe/Documents/Data extractions from I-CAH/Feb 2025/I-CAH_data_Feb_2025/all_therapy_22-25_single.csv", row.names = F)


```

```{r : med box plots raw values}
# using MDBoxPlot function

## Dexamethasone
DexamethasoneBoxPlot_22_23 <- MDBoxPlot(therapy_22_23_single[therapy_22_23_single$Medicine_1.x == "Dexamethasone",], "Total_raw_dose", "None", "total daily dose dexamethasone 22-23")

DexamethasoneBoxPlot_23_25 <- MDBoxPlot(therapy_23_25_single[therapy_23_25_single$Medicine_1.x == "Dexamethasone",], "Total_raw_dose", "None", "total daily dose dexamethasone 23-25")

DexamethasoneBoxPlot_all <- MDBoxPlot(all_therapy_22_25_single[all_therapy_22_25_single$Medicine_1.x == "Dexamethasone",], "Total_raw_dose", "None", "total daily dose dexamethasone 22-25")

## Efmody
EfmodyBoxPlot_22_23 <- MDBoxPlot(therapy_22_23_single[therapy_22_23_single$Medicine_1.x == "Efmody",], "Total_raw_dose", "None", "total daily dose efmody 22-23")

EfmodyBoxPlot_23_25 <- MDBoxPlot(therapy_23_25_single[therapy_23_25_single$Medicine_1.x == "Efmody",], "Total_raw_dose", "None", "total daily dose efmody 23-25")

EfmodyBoxPlot_all <- MDBoxPlot(all_therapy_22_25_single[all_therapy_22_25_single$Medicine_1.x == "Efmody",], "Total_raw_dose", "None", "total daily dose efmody 22-25")

## Hydrocortisone
HydrocortisoneBoxPlot_22_23 <- MDBoxPlot(therapy_22_23_single[therapy_22_23_single$Medicine_1.x == "Hydrocortisone",], "Total_raw_dose", "None", "total daily dose hydro 22-23")

HydrocortisoneBoxPlot_23_25 <- MDBoxPlot(therapy_23_25_single[therapy_23_25_single$Medicine_1.x == "Hydrocortisone",], "Total_raw_dose", "None", "total daily dose hydro 23-25")

HydrocortisoneBoxPlot_all <- MDBoxPlot(all_therapy_22_25_single[all_therapy_22_25_single$Medicine_1.x == "Hydrocortisone",], "Total_raw_dose", "None", "total daily dose hydro 22-25")

## Prednisolone
PrednisoloneBoxPlot_22_23 <- MDBoxPlot(therapy_22_23_single[therapy_22_23_single$Medicine_1.x == "Prednisolone",], "Total_raw_dose", "None", "total daily dose prednisolone 22-23")

PrednisoloneBoxPlot_23_25 <- MDBoxPlot(therapy_23_25_single[therapy_23_25_single$Medicine_1.x == "Prednisolone",], "Total_raw_dose", "None", "total daily dose prednisolone 23-25")

PrednisoloneBoxPlot_23_25 <- MDBoxPlot(all_therapy_22_25_single[all_therapy_22_25_single$Medicine_1.x == "Prednisolone",], "Total_raw_dose", "None", "total daily dose prednisolone 22-25")
```

```{r : med box plots HC equivalent}
# using MDBoxPlot function
# don't need to do HC here since this is the medicine to which the others have been standardised.
# also don't need to do Efmody since this is already equivalent.

equiv_DexamethasoneBoxPlot_22_23 <- MDBoxPlot(therapy_22_23_single[therapy_22_23_single$Medicine_1.x == "Dexamethasone",], "HC_equivalent_daily_dose_1_1", "None", "HC equivalent daily dose dexamethasone 22-23")

equiv_DexamethasoneBoxPlot_23_25 <- MDBoxPlot(therapy_23_25_single[therapy_23_25_single$Medicine_1.x == "Dexamethasone",], "HC_equivalent_daily_dose_1_1", "None", "HC equivalent daily dose dexamethasone 23-25")

equiv_DexamethasoneBoxPlot_all <- MDBoxPlot(all_therapy_22_25_single[all_therapy_22_25_single$Medicine_1.x == "Dexamethasone",], "HC_equivalent_daily_dose_1_1", "None", "HC equivalent daily dose dexamethasone 22-25")

equiv_PrednisoloneBoxPlot_22_23 <- MDBoxPlot(therapy_22_23_single[therapy_22_23_single$Medicine_1.x == "Prednisolone",], "HC_equivalent_daily_dose_1_1", "None", "HC equivalent daily dose prednisolone 22-23")

equiv_PrednisoloneBoxPlot_23_25 <- MDBoxPlot(therapy_23_25_single[therapy_23_25_single$Medicine_1.x == "Prednisolone",], "HC_equivalent_daily_dose_1_1", "None", "HC equivalent daily dose prednisolone 23-25")

equiv_PrednisoloneBoxPlot_all <- MDBoxPlot(all_therapy_22_25_single[all_therapy_22_25_single$Medicine_1.x == "Prednisolone",], "HC_equivalent_daily_dose_1_1", "None", "HC equivalent daily dose prednisolone 22-25")
```

```{r : med box plots dose per BSA values}
# using MDBoxPlot function

## Dexamethasone
HC_equiv_BSA_DexamethasoneBoxPlot_22_23 <- MDBoxPlot(therapy_22_23_single[therapy_22_23_single$Medicine_1.x == "Dexamethasone",], "HC_equivalent_daily_dose_per_BSA", "None", "HC equiv per BSA total daily dose dexamethasone 22-23")

HC_equiv_BSA_DexamethasoneBoxPlot_23_25 <- MDBoxPlot(therapy_23_25_single[therapy_23_25_single$Medicine_1.x == "Dexamethasone",], "HC_equivalent_daily_dose_per_BSA", "None", "HC equiv per BSA total daily dose dexamethasone 23-25")

HC_equiv_BSA_DexamethasoneBoxPlot_all <- MDBoxPlot(all_therapy_22_25_single[all_therapy_22_25_single$Medicine_1.x == "Dexamethasone",], "HC_equivalent_daily_dose_per_BSA", "None", "HC equiv per BSA total daily dose dexamethasone 22-25")


## Efmody
HC_equiv_BSA_EfmodyBoxPlot_22_23 <- MDBoxPlot(therapy_22_23_single[therapy_22_23_single$Medicine_1.x == "Efmody",], "HC_equivalent_daily_dose_per_BSA", "None", "HC equiv per BSA total daily dose efmody 22-23")

HC_equiv_BSA_EfmodyBoxPlot_23_25 <- MDBoxPlot(therapy_23_25_single[therapy_23_25_single$Medicine_1.x == "Efmody",], "HC_equivalent_daily_dose_per_BSA", "None", "HC equiv per BSA total daily dose efmody 23-25")

HC_equiv_BSA_EfmodyBoxPlot_22_25 <- MDBoxPlot(all_therapy_22_25_single[all_therapy_22_25_single$Medicine_1.x == "Efmody",], "HC_equivalent_daily_dose_per_BSA", "None", "HC equiv per BSA total daily dose efmody 22-25")


## Hydrocortisone
HC_equiv_BSA_HydrocortisoneBoxPlot_22_23 <- MDBoxPlot(therapy_22_23_single[therapy_22_23_single$Medicine_1.x == "Hydrocortisone",], "HC_equivalent_daily_dose_per_BSA", "None", "HC per BSA total daily dose hydro 22-23")

HC_equiv_BSA_HydrocortisoneBoxPlot_23_25 <- MDBoxPlot(therapy_23_25_single[therapy_23_25_single$Medicine_1.x == "Hydrocortisone",], "HC_equivalent_daily_dose_per_BSA", "None", "HC per BSA total daily dose hydro 23-25") + ylim(0,25)

HC_equiv_BSA_HydrocortisoneBoxPlot_22_25 <- MDBoxPlot(all_therapy_22_25_single[all_therapy_22_25_single$Medicine_1.x == "Hydrocortisone",], "HC_equivalent_daily_dose_per_BSA", "None", "HC per BSA total daily dose hydro 22-25") + ylim(0,25) +   annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=15, alpha=.5, fill='grey') + geom_hline(yintercept = 11, colour = "red")


## Prednisolone
HC_equiv_BSA_PrednisoloneBoxPlot_22_23 <- MDBoxPlot(therapy_22_23_single[therapy_22_23_single$Medicine_1.x == "Prednisolone",], "HC_equivalent_daily_dose_per_BSA", "None", "HC equiv per BSA total daily dose prednisolone 22-23")

HC_equiv_BSA_PrednisoloneBoxPlot_23_25 <- MDBoxPlot(therapy_23_25_single[therapy_23_25_single$Medicine_1.x == "Prednisolone",], "HC_equivalent_daily_dose_per_BSA", "None", "HC equiv per BSA total daily dose prednisolone 23-25")

HC_equiv_BSA_PrednisoloneBoxPlot_22_25 <- MDBoxPlot(all_therapy_22_25_single[all_therapy_22_25_single$Medicine_1.x == "Prednisolone",], "HC_equivalent_daily_dose_per_BSA", "None", "HC equiv per BSA total daily dose prednisolone 22-25")  +   annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=15, alpha=.5, fill='grey') + geom_hline(yintercept = 11, colour = "red")
```


```{r : dose time histograms}
# using medTimePlot function
# this is for all data across all centres

Dex_dose_times_22_23 <- medTimePlot(therapy_22_23_single, "Dexamethasone", "Dexamethasone dose timing (22-23)")

Dex_dose_times_23_25 <- medTimePlot(therapy_23_25_single, "Dexamethasone", "Dexamethasone dose timing (23-25)")

Dex_dose_times_all <- medTimePlot(all_therapy_22_25_single, "Dexamethasone", "Dexamethasone dose timing (22-25)")

Efmody_dose_times_22_23 <- medTimePlot(therapy_22_23_single, "Efmody", "Efmody dose timing (22-23)")

Efmody_dose_times_23_25 <- medTimePlot(therapy_23_25_single, "Efmody", "Efmody dose timing (23-25)")

Efmody_dose_times_all <- medTimePlot(all_therapy_22_25_single, "Efmody", "Efmody dose timing (22-25)")

HC_dose_times_22_23 <- medTimePlot(therapy_22_23_single, "Hydrocortisone", "HC dose timing (22-23)")

HC_dose_times_23_25 <- medTimePlot(therapy_23_25_single, "Hydrocortisone", "HC dose timing (23-25)")

HC_dose_times_all <- medTimePlot(all_therapy_22_25_single, "Hydrocortisone", "HC dose timing (22-25)")

Pred_dose_times_22_23 <- medTimePlot(therapy_22_23_single, "Prednisolone", "Pred dose timing (22-23)")

Pred_dose_times_23_25 <- medTimePlot(therapy_23_25_single, "Prednisolone", "Pred dose timing (23-35)")

Pred_dose_times_all <- medTimePlot(all_therapy_22_25_single, "Prednisolone", "Pred dose timing (22-25)")
```

```{r : raw dose stats}
raw_dex_doses_22_23 <- summariseMed(therapy_22_23_single, "Dexamethasone", "raw")

raw_dex_doses_23_25 <- summariseMed(therapy_23_25_single, "Dexamethasone", "raw")

raw_dex_doses_all <- summariseMed(all_therapy_22_25_single, "Dexamethasone", "raw")

raw_efmody_doses_22_23 <- summariseMed(therapy_22_23_single, "Efmody", "raw")

raw_efmody_doses_23_25 <- summariseMed(therapy_23_25_single, "Efmody", "raw")

raw_efmody_doses_all <- summariseMed(all_therapy_22_25_single, "Efmody", "raw")

raw_HC_doses_22_23 <- summariseMed(therapy_22_23_single, "Hydrocortisone", "raw")

raw_HC_doses_23_25 <- summariseMed(therapy_23_25_single, "Hydrocortisone", "raw")

raw_HC_doses_all <- summariseMed(all_therapy_22_25_single, "Hydrocortisone", "raw")

raw_pred_doses_22_23 <- summariseMed(therapy_22_23_single, "Prednisolone", "raw")

raw_pred_doses_23_25 <- summariseMed(therapy_23_25_single, "Prednisolone", "raw")

raw_pred_doses_all <- summariseMed(all_therapy_22_25_single, "Prednisolone", "raw")
```

```{r : HC equivalent dose stats}
equiv_dex_doses_22_23 <- summariseMed(therapy_22_23_single, "Dexamethasone", "equiv")

equiv_dex_doses_23_25 <- summariseMed(therapy_23_25_single, "Dexamethasone", "equiv")

equiv_dex_doses_all <- summariseMed(all_therapy_22_25_single, "Dexamethasone", "equiv")

equiv_pred_doses_22_23 <- summariseMed(therapy_22_23_single, "Prednisolone", "equiv")

equiv_pred_doses_23_25 <- summariseMed(therapy_23_25_single, "Prednisolone", "equiv")

equiv_pred_doses_all <- summariseMed(all_therapy_22_25_single, "Prednisolone", "equiv")
```

```{r : HC equivalent per BSA dose stats}
# error to fix
equiv_BSA_dex_doses_22_23 <- summariseMed(therapy_22_23_single, "Dexamethasone", "BSA")

equiv_BSA_dex_doses_23_25 <- summariseMed(therapy_23_25_single, "Dexamethasone", "BSA")

equiv_BSA_dex_doses_all <- summariseMed(all_therapy_22_25_single, "Dexamethasone", "BSA")

equiv_BSA_pred_doses_22_23 <- summariseMed(therapy_22_23_single, "Prednisolone", "BSA")

equiv_BSA_pred_doses_23_25 <- summariseMed(therapy_23_25_single, "Prednisolone", "BSA")

equiv_BSA_pred_doses_all <- summariseMed(all_therapy_22_25_single, "Prednisolone", "BSA")
```


```{r : therapy dose trends}
therapy_22_23_single$Centre.ID.x <- as.factor(therapy_22_23_single$Centre.ID.x)
therapy_23_25_single$Centre.ID.x <- as.factor(therapy_23_25_single$Centre.ID.x)
all_therapy_22_25_single$Centre.ID.x <- as.factor(all_therapy_22_25_single$Centre.ID.x)

therapy_dose_trends_22_23 <- ggplot(therapy_22_23_single, aes(x = Centre.ID.x, y = HC_equivalent_daily_dose_1_1, fill = Medicine_1.x)) +
  geom_boxplot(position = position_dodge2(preserve='single'),) +
  ggtitle("therapy dose trends 22-23") +
  theme_minimal() +
  geom_point(position = position_dodge(width = 0.75))

therapy_dose_trends_23_25 <- ggplot(therapy_23_25_single, aes(x = Centre.ID.x, y = HC_equivalent_daily_dose_1_1, fill = Medicine_1.x)) +
  geom_boxplot(position = position_dodge2(preserve='single'),) +
  ggtitle("therapy dose trends 23-25") +
  theme_minimal() +
  geom_point(position = position_dodge(width = 0.75))

therapy_dose_trends_all <- ggplot(all_therapy_22_25_single, aes(x = Centre.ID.x, y = HC_equivalent_daily_dose_1_1, fill = Medicine_1.x)) +
  geom_boxplot(position = position_dodge2(preserve='single'),) +
  ggtitle("therapy dose trends 23-25") +
  theme_minimal() +
  geom_point(position = position_dodge(width = 0.75))
```


```{r : therapy dose trends with facet wrap - HC equivalent total daily doses}
therapy_dose_trends_22_23 <- ggplot(therapy_22_23_single, aes(x = Centre.ID.x, y = HC_equivalent_daily_dose_1_1, fill = Medicine_1.x)) +
  geom_boxplot() +
  ggtitle("therapy dose trends 22-23") +
  facet_wrap(~ Medicine_1.x, axes = "all", axis.labels = "all") +
  theme_minimal() +
  geom_point(position = position_dodge(width = 0.75))

therapy_dose_trends_23_25 <- ggplot(therapy_23_25_single, aes(x = Centre.ID.x, y = HC_equivalent_daily_dose_1_1, fill = Medicine_1.x)) +
  geom_boxplot() +
  ggtitle("therapy dose trends 23-25") +
  facet_wrap(~ Medicine_1.x, axes = "all", axis.labels = "all") +
  theme_minimal() +
  geom_point(position = position_dodge(width = 0.75))

therapy_dose_trends_all <- ggplot(all_therapy_22_25_single, aes(x = Centre.ID.x, y = HC_equivalent_daily_dose_1_1, fill = Medicine_1.x)) +
  geom_boxplot() +
  ggtitle("therapy dose trends 22-25") +
  facet_wrap(~ Medicine_1.x, axes = "all", axis.labels = "all") +
  theme_minimal() +
  geom_point(position = position_dodge(width = 0.75))
```

```{r : HC equiv per BSA doses}
perBSA_therapy_dose_trends_all <- ggplot(all_therapy_22_25_single, aes(x = Centre.ID.x, y = HC_equivalent_daily_dose_per_BSA, fill = Medicine_1.x)) +
  geom_boxplot() +
  ggtitle("HC equivalent total daily dose per BSA 22-25") +
  facet_wrap(~ Medicine_1.x, axes = "all", axis.labels = "all") +
  theme_classic() +
  geom_point(position = position_dodge(width = 0.75)) +
  theme(axis.text.x = element_text(angle=90)) +
  ylim(0,50) +   annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=15, alpha=.5, fill='grey') + geom_hline(yintercept = 11, colour = "red")

perBSA_therapy_dose_trends_all_2 <- ggplot(all_therapy_22_25_single, aes(x = Centre.ID.x, y = HC_equivalent_daily_dose_per_BSA)) +
  geom_boxplot() +
  ggtitle("HC equivalent total daily dose per BSA 22-25") +
  theme_classic() +
  geom_point(position = position_dodge(width = 0.75)) +
  ylim(0,50)  +   annotate('rect', xmin=-Inf, xmax=Inf, ymin=10, ymax=15, alpha=.5, fill='grey') + geom_hline(yintercept = 11, colour = "red")

zoom_perBSA_therapy_dose_trends_all <- perBSA_therapy_dose_trends_all + coord_cartesian(ylim = c(0,20))

zoom_perBSA_therapy_dose_trends_all_2 <- perBSA_therapy_dose_trends_all_2 + coord_cartesian(ylim = c(0,20))
```

```{r : total daily dose vs BMI}
# HC equiv total daily dose vs BMI
test <- ggplot(all_therapy_22_25_single, aes(x = BMI , y = HC_equivalent_daily_dose_1_1)) +
  geom_bin2d() +
  theme_classic()

# HC equiv total daily dose vs weight
test2 <- ggplot(all_therapy_22_25_single, aes(x = Weight..kg. , y = HC_equivalent_daily_dose_1_1)) +
  geom_bin2d() +
  theme_classic()
```

```{r}
# how many patients are on single and combined therapies per centre




```




```{r : checks}
HC_equiv_BSA_under_8_to_check <- subset(all_therapy_22_25_single, HC_equivalent_daily_dose_per_BSA < 8)
write.csv(HC_equiv_BSA_under_8_to_check, "C:/Users/md1rwe/Documents/Data extractions from I-CAH/Feb 2025/I-CAH_data_Feb_2025/HC_equiv_BSA_under_8_to_check.csv", row.names = F)

# individual HC doses <5mg
HC_meds <- subset(all_therapy_22_25_single, Medicine_1.x == "Hydrocortisone")
HC_doses_to_check <- subset(HC_meds, Dose_1 < 5 | Dose_2 <5 | Dose_3 <5 | Dose_4 <5)
write.csv(HC_doses_to_check, "C:/Users/md1rwe/Documents/Data extractions from I-CAH/Feb 2025/I-CAH_data_Feb_2025/HC_doses_to_check.csv", row.names = F)

# individual Pred doses of >5mg
Pred_meds <- subset(all_therapy_22_25_single, Medicine_1.x == "Prednisolone")
Pred_doses_to_check <- subset(Pred_meds, Dose_1 >5 | Dose_2 >5 | Dose_3 >5 | Dose_4 >5)
write.csv(Pred_doses_to_check, "C:/Users/md1rwe/Documents/Data extractions from I-CAH/Feb 2025/I-CAH_data_Feb_2025/Pred_doses_to_check.csv", row.names = F)
```


```{r : script completion message}
print("Script complete")

```